(SUP-3688) Plans to provision and import metrics
puppetlabs/puppet_operational_dashboards pull request #87
Opened 2022-10-03 17:00 UTC by m0dular

This commit adds two Puppet Plans to provision a dashboard node and
import archive metrics from a PE support script.

2022-10-04 16:29 UTC, jarretlavallee requested changes
Looks good to me. I added a couple of nit picks and one potential problem.

2022-10-06 16:53 UTC, m0dular commented on plans/load_metrics.pp
> +        source => "puppet:///modules/puppet_operational_dashboards/scripts/${script}",
I'm honestly not sure to call these scripts or config files, they're kind of both.  They do have code that gets executed, but they're also parameters to the `--config-directory` flag.  What directory do you think they should go in?

2022-10-06 16:54 UTC, m0dular commented on plans/load_metrics.pp
> +      token => Sensitive(Deferred('influxdb::retrieve_token', ["http://${targets}:8086", $telegraf_token, $token_file])),
Should we loop over each target, or enforce that the plan only accepts a single one?

2022-10-06 16:56 UTC, m0dular commented on plans/load_metrics.pp
> +  String $metrics_dir,
Agreed, I feel like this should be a convention enforced by PDK?

2022-10-06 17:06 UTC, jarretlavallee commented on plans/load_metrics.pp
> +        source => "puppet:///modules/puppet_operational_dashboards/scripts/${script}",
At the end of the day, it doesn't really matter. How about neither and go with something that denotes that these are files that the plans use or denote the purpose? `archive`, `plan_files` or something better

2022-10-06 17:07 UTC, jarretlavallee commented on plans/load_metrics.pp
> +      token => Sensitive(Deferred('influxdb::retrieve_token', ["http://${targets}:8086", $telegraf_token, $token_file])),
I can't see a reason that target would be more than one. Is there a use case for that? Maybe we just force it to be one and error out if there is more than one. At that point, we would have a use case to make a change to it.

2022-10-06 17:21 UTC, m0dular commented on plans/load_metrics.pp
> +      token => Sensitive(Deferred('influxdb::retrieve_token', ["http://${targets}:8086", $telegraf_token, $token_file])),
I could _maybe_ see wanting to ship metrics from one archive to multiple InfluxDB hosts, but that's probably very fringe.  We can enforce only a single target, at least for now.

2022-10-10 19:19 UTC, jarretlavallee approved these changes

2022-10-11 09:21 UTC, merged